sudo: required
services:
  - docker

before_install:
  - docker build -t itay19/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true itay19/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react-2"
  env: "Docker-react-2-env"
  bucket_name: "elasticbeanstalk-eu-north-1-038065355703"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $access_key
  secret_access_key: "$secret_key"